## Source-from-tarball libtool recipe — M9.N Batch D build-tool slice.
##
## libtool is the GNU build system's library-compilation abstraction
## layer: it hides the per-platform shared-library quirks (RPATH /
## SONAME / DT_NEEDED / -fPIC / .la archive metadata) behind a
## uniform ``./libtool --mode=compile`` / ``./libtool --mode=link``
## CLI. Autotools projects that build shared libraries
## (``--disable-static`` and friends) drive libtool from their
## generated ``Makefile``s for every compilation + link step.
##
## ## Convention chosen — ``from-source-autotools``
##
## libtool is itself an autotools-driven project: the upstream
## release tarball ships a ``./configure`` script generated by
## autoconf + ``Makefile.in`` files generated by automake. The
## ``from-source-autotools`` convention (M9.L.2) claims the recipe
## via the populated ``configureFlags:`` channel.
##
## ## Why libtool matters for the v1 desktop story
##
## libtool is the shared-library abstraction every autotools-driven
## C / C++ recipe in ``recipes/packages/source/`` that produces a
## shared object depends on: expat, libcap, libcap-ng, gettext, xz,
## ncurses, readline, libffi, libgcrypt, libxml2, nettle, gnutls,
## libtasn1, libidn2, gawk, ... all drive ``./libtool`` from their
## ``Makefile``s. Bootstrapping libtool from source closes the
## ``uses: "libtool"`` toolchain floor those recipes pin.
##
## ## sha256 strategy
##
## The fetch URL points at the upstream ftp.gnu.org release tarball
## ``libtool-2.5.4.tar.xz``. The sha256 was computed locally by
## downloading the ``.tar.xz`` variant and running ``sha256sum`` over
## the bytes. nixpkgs's
## ``pkgs/development/tools/misc/libtool/libtool2.nix`` pins libtool
## 2.5.4 but consumes the ``.tar.gz`` variant with SRI
## ``sha256-2o67LOTc9GuQCY2vliz/po9LT2LqYPeY0O8Skp7eat8=`` — NOT the
## ``.tar.xz`` variant the task brief requests, so the nixpkgs cross-
## check is byte-incompatible (different compressor).
##
## ## Version choice — 2.5.4 (per task brief; matches nixpkgs)
##
## libtool releases are cut on ftp.gnu.org under tags of the form
## ``libtool-<X>.<Y>.<Z>``. 2.5.4 is the current stable in the 2.5.x
## line and the same version nixpkgs pins; anything ``>=2.4`` covers
## every consumer's libtool pinning.
##
## ## Artifacts
##
## libtool exposes two load-bearing CLI binaries + one library on
## disk:
##
##   * ``libtool``    — ``$PREFIX/bin/libtool``, the canonical shell
##                       driver that wraps compile / link / install /
##                       finish / execute operations behind a uniform
##                       CLI.
##   * ``libtoolize`` — ``$PREFIX/bin/libtoolize``, the per-project
##                       libtool installer driven by ``autoreconf``.
##   * ``libltdl``    — ``$PREFIX/lib/libltdl.so``, the dynamic-module
##                       loader library autotools projects link
##                       against when they need to ``dlopen``-style
##                       load plugins portably.
##
## ## Configurables
##
## v1 ships ONE configure flag — ``--disable-static`` — mirroring the
## modern-desktop baseline. libtool's own libltdl honours the flag
## and emits only the shared variant.

import repro_project_dsl
import repro_dsl_stdlib/constructors
import repro_dsl_stdlib/types/package_result

# ---------------------------------------------------------------------------
# Package declaration
# ---------------------------------------------------------------------------

package libtoolSource:
  ## From-source libtool — M9.N Batch D build-tool slice.
  ##
  ## Tier-2b from-source-autotools convention consumer: the
  ## convention layer reads the ``fetch:`` block (registered via
  ## ``registeredFetchSpec``) and the ``configureFlags:`` block
  ## (registered via ``registeredBuildFlags`` on the ``"configure"``
  ## channel) and lowers them into fetch + configure + build + install
  ## BuildActions. Mixed-kind two-executable + one-library artifact
  ## recipe.

  versions:
    ## Pinned upstream tag. ``sourceUrl`` records the canonical
    ## ftp.gnu.org release tarball URL; ``sourceRepository`` points
    ## at the canonical savannah.gnu.org mirror.
    "2.5.4":
      sourceRevision = "v2.5.4"
      sourceUrl = "https://ftp.gnu.org/gnu/libtool/libtool-2.5.4.tar.xz"
      sourceRepository = "https://git.savannah.gnu.org/git/libtool.git"

  fetch:
    ## Live upstream URL. The vendor/ directory is reserved for a
    ## follow-up vendoring pass.
    ##
    ## sha256 computed locally over the upstream ftp.gnu.org
    ## ``.tar.xz`` tarball; nixpkgs cross-check is byte-incompatible
    ## because nixpkgs consumes the ``.tar.gz`` variant.
    url: "https://ftp.gnu.org/gnu/libtool/libtool-2.5.4.tar.xz"
    sha256: "f81f5860666b0bc7d84baddefa60d1cb9fa6fceb2398cc3baca6afaa60266675"
    extractStrip: 1

  nativeBuildDeps:
    ## m4 is the macro processor libtool's bootstrap chain shells out
    ## to for the ``libtool.m4`` macro expansion.
    "m4"
    ## make is the build-system driver — the from-source-autotools
    ## convention's compile action invokes ``make`` after
    ## ``./configure``.
    "make"
    ## gcc is the host C toolchain — libltdl is C99.
    "gcc >=11"

  buildDeps:
    ## file is consumed by libtool 2.4.7+ for the ``FILECMD`` shim
    ## that replaces the hardcoded ``/usr/bin/file`` reference.
    "file"

  config:
    ## No prefix lifted from `configureFlags:`; flags inlined in the `build:` block.
    discard
  executable libtool:
    ## ``$PREFIX/bin/libtool`` — the canonical shell driver wrapping
    ## compile / link / install / finish / execute operations. v1
    ## records the artifact only.
    discard

  executable libtoolize:
    ## ``$PREFIX/bin/libtoolize`` — the per-project libtool installer
    ## driven by ``autoreconf``. v1 records the artifact only.
    discard

  library libltdl:
    ## ``$PREFIX/lib/libltdl.so`` — the dynamic-module loader library
    ## autotools projects link against when they need portable
    ## ``dlopen`` semantics. v1 records the artifact only.
    discard

  build:
    ## M9.R.5b — explicit `build:` block constructed from the lifted `config:` values + the inlined verbatim flags. Calls the M9.R.2b high-level `autotools_package(...)` constructor.
    setCurrentOwningPackageOverride("libtoolSource")
    try:
      let opts = @[
        "--disable-static",
      ]
      let pkg = autotools_package(srcDir = "./src", configureOptions = opts)
      discard pkg.executable("libtool")
      discard pkg.executable("libtoolize")
      discard pkg.library("libltdl")
    finally:
      clearCurrentOwningPackageOverride()

  runtimeDeps:
    ## TODO(M9.R.5b): derive runtime closure from pkg-config /
    ## DT_NEEDED inspection of the linked artifacts. Empty until
    ## the M9.R.5b per-recipe pass populates per-output ELF
    ## interrogation.
    discard
