## Source-from-tarball autoconf recipe — M9.N Batch D build-tool slice.
##
## autoconf is the GNU build system's source-configuration generator:
## it processes ``configure.ac`` templates into portable ``./configure``
## shell scripts. The upstream tarball ships a pre-generated
## ``./configure`` (the canonical autotools pre-bootstrap) so the
## standard ``./configure && make && make install`` cycle suffices.
##
## ## Convention chosen — ``from-source-autotools``
##
## autoconf is itself an autotools-driven project: the upstream
## release tarball ships a ``./configure`` script generated by a
## prior autoconf bootstrap, plus the ``Makefile.in`` templates the
## autoconf install body assembles. The ``from-source-autotools``
## convention (M9.L.2) claims the recipe via the populated
## ``configureFlags:`` channel.
##
## ## Why autoconf matters for the v1 desktop story
##
## autoconf is the source-configuration generator the entire C / C++
## ecosystem relies on: every autotools-driven recipe in
## ``recipes/packages/source/`` (expat, fontconfig, coreutils, sed,
## grep, less, bash, ncurses, readline, libcap, libcap-ng, eudev,
## util-linux, gawk, pam, libffi, ...) re-bootstraps ``./configure``
## from ``configure.ac`` when the shipped script is missing or stale.
## Bootstrapping autoconf from source closes the
## ``uses: "autoconf"`` toolchain floor every autotools-driven
## upstream tarball needs at build time.
##
## ## sha256 strategy
##
## The fetch URL points at the upstream ftp.gnu.org release tarball
## ``autoconf-2.72.tar.xz``. The sha256 was computed locally by
## downloading the tarball and running ``sha256sum`` over the bytes.
## nixpkgs's ``pkgs/development/tools/misc/autoconf/default.nix`` pins
## autoconf 2.73 with SRI
## ``sha256-n9ZyschCX6wvpn+gR3uZCYcmi5D/NtXwFtrle+DWtS4=``, NOT the
## 2.72 release the task brief requests, so the nixpkgs cross-check
## is deferred to the follow-up pass that lifts autoconf to nixpkgs's
## 2.73 pinning.
##
## ## Version choice — 2.72 (per task brief)
##
## autoconf releases are cut on ftp.gnu.org under tags of the form
## ``autoconf-<X>.<Y><...>``. 2.72 is the last stable in the 2.7x
## line before 2.73 the task brief explicitly requested; anything
## ``>=2.69`` covers every consumer's autoconf pinning.
##
## ## Artifacts
##
## autoconf exposes seven load-bearing CLI binaries on disk:
##
##   * ``autoconf``   — ``$PREFIX/bin/autoconf``, the canonical
##                       ``configure.ac`` → ``./configure`` generator.
##   * ``autoheader`` — ``$PREFIX/bin/autoheader``, generates
##                       ``config.h.in`` from ``configure.ac``.
##   * ``autom4te``   — ``$PREFIX/bin/autom4te``, the underlying M4
##                       macro-expansion engine the other autoconf
##                       drivers shell out to.
##   * ``autoreconf`` — ``$PREFIX/bin/autoreconf``, the
##                       re-bootstrap driver that runs autoconf +
##                       autoheader + automake + libtoolize in one
##                       step.
##   * ``autoscan``   — ``$PREFIX/bin/autoscan``, scans a source tree
##                       and emits a draft ``configure.scan``.
##   * ``autoupdate`` — ``$PREFIX/bin/autoupdate``, rewrites a
##                       ``configure.ac`` to use the current macro
##                       set.
##   * ``ifnames``    — ``$PREFIX/bin/ifnames``, helper for
##                       enumerating preprocessor identifiers.
##
## ## Configurables
##
## v1 ships ONE configure flag — ``--disable-static`` — mirroring the
## modern-desktop baseline per the task brief. autoconf itself is
## Perl-implemented so the static/shared distinction barely applies,
## but the flag is preserved for consistency with the other autotools
## recipes (expat / coreutils / xz / ...) so a regression that
## defaulted ``configureFlags`` to empty on this recipe would surface
## as a flag-count mismatch.

import repro_project_dsl
import repro_dsl_stdlib/constructors
import repro_dsl_stdlib/types/package_result

# ---------------------------------------------------------------------------
# Package declaration
# ---------------------------------------------------------------------------

package autoconfSource:
  ## From-source autoconf — M9.N Batch D build-tool slice.
  ##
  ## Tier-2b from-source-autotools convention consumer: the
  ## convention layer reads the ``fetch:`` block (registered via
  ## ``registeredFetchSpec``) and the ``configureFlags:`` block
  ## (registered via ``registeredBuildFlags`` on the ``"configure"``
  ## channel) and lowers them into fetch + configure + build + install
  ## BuildActions. Seven executable artifact recipe.

  versions:
    ## Pinned upstream tag. ``sourceUrl`` records the canonical
    ## ftp.gnu.org release tarball URL; ``sourceRepository`` points
    ## at the canonical savannah.gnu.org mirror.
    "2.72":
      sourceRevision = "v2.72"
      sourceUrl = "https://ftp.gnu.org/gnu/autoconf/autoconf-2.72.tar.xz"
      sourceRepository = "https://git.savannah.gnu.org/git/autoconf.git"

  fetch:
    ## Live upstream URL. The vendor/ directory is reserved for a
    ## follow-up vendoring pass.
    ##
    ## sha256 computed locally over the upstream ftp.gnu.org tarball;
    ## nixpkgs cross-check deferred because nixpkgs pins autoconf 2.73
    ## (not the 2.72 the task brief requests).
    url: "https://ftp.gnu.org/gnu/autoconf/autoconf-2.72.tar.xz"
    sha256: "ba885c1319578d6c94d46e9b0dceb4014caafe2490e437a0dbca3f270a223f5a"
    extractStrip: 1

  nativeBuildDeps:
    ## m4 is the macro processor autoconf shells out to for the
    ## ``configure.ac`` → ``./configure`` template expansion.
    "m4"
    ## perl is the implementation language for autoconf's CLI drivers
    ## and the autom4te cache layer.
    "perl >=5.32"
    ## make is the build-system driver — the from-source-autotools
    ## convention's compile action invokes ``make`` after
    ## ``./configure``.
    "make"

  config:
    ## No prefix lifted from `configureFlags:`; flags inlined in the `build:` block.
    discard
  executable autoconf:
    ## ``$PREFIX/bin/autoconf`` — the canonical ``configure.ac`` →
    ## ``./configure`` generator. v1 records the artifact only.
    discard

  executable autoheader:
    ## ``$PREFIX/bin/autoheader`` — generates ``config.h.in`` from
    ## ``configure.ac``. v1 records the artifact only.
    discard

  executable autom4te:
    ## ``$PREFIX/bin/autom4te`` — the underlying M4 macro-expansion
    ## engine the other autoconf drivers shell out to. v1 records the
    ## artifact only.
    discard

  executable autoreconf:
    ## ``$PREFIX/bin/autoreconf`` — the re-bootstrap driver that runs
    ## autoconf + autoheader + automake + libtoolize in one step.
    ## v1 records the artifact only.
    discard

  executable autoscan:
    ## ``$PREFIX/bin/autoscan`` — scans a source tree and emits a
    ## draft ``configure.scan``. v1 records the artifact only.
    discard

  executable autoupdate:
    ## ``$PREFIX/bin/autoupdate`` — rewrites a ``configure.ac`` to
    ## use the current macro set. v1 records the artifact only.
    discard

  executable ifnames:
    ## ``$PREFIX/bin/ifnames`` — helper for enumerating preprocessor
    ## identifiers. v1 records the artifact only.
    discard

  build:
    ## M9.R.5b — explicit `build:` block constructed from the lifted `config:` values + the inlined verbatim flags. Calls the M9.R.2b high-level `autotools_package(...)` constructor.
    setCurrentOwningPackageOverride("autoconfSource")
    try:
      let opts = @[
        "--disable-static",
      ]
      let pkg = autotools_package(srcDir = "./src", configureOptions = opts)
      discard pkg.executable("autoconf")
      discard pkg.executable("autoheader")
      discard pkg.executable("autom4te")
      discard pkg.executable("autoreconf")
      discard pkg.executable("autoscan")
      discard pkg.executable("autoupdate")
      discard pkg.executable("ifnames")
    finally:
      clearCurrentOwningPackageOverride()

  runtimeDeps:
    ## TODO(M9.R.5b): derive runtime closure from pkg-config /
    ## DT_NEEDED inspection of the linked artifacts. Empty until
    ## the M9.R.5b per-recipe pass populates per-output ELF
    ## interrogation.
    discard
