## `nixfmt` from source -- the catalog's Windows realization of `nixfmt`.
##
## Nothing publishes a Windows nixfmt (upstream attaches only a static x86_64
## Linux binary; nixpkgs, Scoop, MSYS2 and conda-forge carry none), so on
## Windows the formatter is built here, from upstream's 1.2.0 tag, with GHC
## and cabal-install from reprobuild's stdlib (`ghc` 9.12.1, `cabal`
## 3.16.1.0) and the `cabal_package` constructor.
##
## ## Why it needs a patch, and how small it is
##
## The `nixfmt` LIBRARY is portable Haskell. The EXECUTABLE is not, for three
## reasons, all in `main/`:
##
## * `nixfmt.cabal` makes the executable depend on `unix`, which declares
##   itself unbuildable on Windows;
## * `main/Main.hs` installs a SIGINT handler that exits at once
##   (`System.Posix.Signals.installHandler keyboardSignal`,
##   `System.Posix.Process.exitImmediately`);
## * `main/System/IO/Atomic.hs` copies the original file's POSIX mode and
##   owner onto the temporary file it renames over it
##   (`System.Posix.Files`).
##
## `patches/nixfmt-1.2.0-windows.patch` makes `unix` a dependency off
## Windows only (`if !os(windows)`), moves the SIGINT handler into a small
## `System.Interrupt` module that installs it off Windows only (on Windows
## GHC's runtime already turns Ctrl-C into an exception), and gives
## `Atomic.hs` a Windows branch that carries the file's permissions over
## through `System.Directory` instead. The handler gets its own module
## because only that module may use CPP: enabling CPP in `Main.hs` breaks the
## string gaps in its help texts (measured: GHC-21231). One more change is needed for the output to be right rather than
## merely to compile: GHC opens text handles on Windows in
## `nativeNewlineMode`, which writes every LF as CRLF, so the formatter would
## rewrite every line ending of a `.nix` file. The patch opens files and the
## standard handles with `noNewlineTranslation`, which is already the mode on
## POSIX -- so output is byte-identical to the Linux build's. It also relaxes `filepath < 1.5` to
## `< 1.6` (upstream dropped the bound in 1.3.0) so GHC 9.12's own `filepath`
## satisfies it; otherwise cabal rebuilds `filepath` and every boot package
## above it, including `time`, whose configure script needs a POSIX shell.
##
## The patch is written to go upstream: every change is Windows-guarded or a
## no-op on POSIX, and the executable's behaviour off Windows is unchanged
## except that the SIGINT handler is not installed on Windows. It has not
## been submitted. Upstream's current release (1.5.0) still depends on
## `unix` unconditionally, so a later version bump needs the same patch
## rebased (the three POSIX uses are still the only ones).
##
## ## The Hackage closure
##
## `hackage-vendor.manifest` pins the 17 Hackage packages the build plan uses
## beyond GHC's boot packages, and the revised `.cabal` files of the four
## whose plan used a Hackage revision. It was generated by
## `tools/hackage_closure_manifest.nim` from the plan cabal 3.16.1.0 solved
## with GHC 9.12.1 for windows-x86_64, from the patched source, at Hackage
## index-state 2026-09-30T00:00:00Z. The build then runs `cabal build` with
## a private `CABAL_DIR` whose only package repository is the vendored one,
## so nothing can come from anywhere else. To refresh after a version bump, from the patched tree:
##
##     export CABAL_DIR=$(mktemp -d)
##     cabal update 'hackage.haskell.org,<index-state>'
##     cabal build exe:nixfmt --dry-run
##     nim r tools/hackage_closure_manifest.nim \
##       --plan=dist-newstyle/cache/plan.json --index-state=<index-state> \
##       --out=packages/source/nixfmt/hackage-vendor.manifest
##
## ## What was measured (Windows x86_64, 2026-10-03)
##
## With GHC 9.12.1 and cabal 3.16.1.0, a private `CABAL_DIR` whose only
## repository was the vendored one, and this patch: the 17 closure packages
## and nixfmt built without network access, and the executable links only
## Windows system DLLs. `nixfmt --version` prints 1.2.0; `nixfmt --check`
## accepts RunQuota's `flake.nix` (formatted by the Linux 1.2.0 build), and
## rewriting it leaves it byte-identical, LF line endings included.
##
## ## Version
##
## 1.2.0: the version the catalog's Linux release binary and RunQuota's flake
## dev shell carry, so `nixfmt` formats the same way on every platform. The
## source is GitHub's tag tarball (nixfmt is not on Hackage past 0.6.0).

import repro_project_dsl
import repro_dsl_stdlib/constructors
import repro_dsl_stdlib/types/package_result

const
  NixfmtVersion = "1.2.0"
  NixfmtSourceUrl =
    "https://github.com/NixOS/nixfmt/archive/refs/tags/v" & NixfmtVersion &
    ".tar.gz"
  NixfmtSourceSha256 =
    "2b148abdf3c2ae9fca2b5898709cde5e4474e09cb32b892da51651c479f1f73a"

package nixfmtSource:
  versions:
    "1.2.0":
      sourceRevision = "v" & NixfmtVersion
      sourceUrl = NixfmtSourceUrl
      sourceRepository = "https://github.com/NixOS/nixfmt.git"

  fetch:
    url: NixfmtSourceUrl
    sha256: NixfmtSourceSha256
    # The tag tarball's single top-level directory is `nixfmt-1.2.0/`.
    extractStrip: 1

  nativeBuildDeps:
    "ghc >=9.12"
    "cabal >=3.16"
    # `git apply` applies the patch to the build's copy of the source.
    "git"

  config:
    discard

  executable nixfmt:
    discard

  build:
    setCurrentOwningPackageOverride("nixfmtSource")
    try:
      let pkg = cabal_package(
        target = "exe:nixfmt",
        patches = @["patches/nixfmt-1.2.0-windows.patch"])
      discard pkg.executable("nixfmt")
    finally:
      clearCurrentOwningPackageOverride()

  runtimeDeps:
    discard
