## Source-from-tarball gobject-introspection recipe — M9.R.15b
## GNOME-stack foundation, prereq of gtk4.
##
## gobject-introspection is the build-time toolchain that scans
## GObject-using C libraries (gtk4, glib2, mutter, ...) and emits
## ``.gir`` (XML) + ``.typelib`` (binary) metadata describing every
## exposed type / method / signal / property. Language bindings
## (gjs / pygobject / Vala) consume the .typelib files to autogenerate
## bindings. gtk4 4.22.x uses gobject-introspection at build time
## even when no .gir / .typelib output is requested — the meson
## ``gnome.generate_gir()`` helper is invoked unconditionally for the
## v1 closure, so the gobject-introspection-1.0 pkg-config probe
## must succeed.
##
## ## Why gobject-introspection matters for the v1 desktop story
##
## NDE-G1 (the GNOME-stack DE entry) currently runs in two modes:
##
##   * **v1 closure** — the introspection output is NOT consumed at
##     runtime; gjs / pygobject are deferred to M9.R.15c, gnome-shell
##     is deferred, no Vala consumer exists yet. But gtk4's meson
##     build still requires ``gobject-introspection-1.0.pc`` and
##     ``g-ir-scanner`` on PATH at configure time (set
##     ``introspection=disabled`` on gtk4's options if you want to
##     skip the dep entirely; v1 keeps it on so the cache key is
##     stable across the M9.R.15c gjs+mozjs landing).
##
##   * **future** — gjs (M9.R.15c) consumes the .typelib for every
##     GObject library in the runtime, gnome-shell's JS extension
##     host depends on the full introspection metadata at runtime.
##
## ## sha256 strategy
##
## Per the network + audio batch convention (alsa-lib + kernel
## precedent): live ``fetch:`` URL points at upstream directly (no
## vendoring). gobject-introspection is published on download.gnome.org
## under the ``mirror://gnome/sources/gobject-introspection/`` alias;
## sha256 cross-checked against nixpkgs's
## ``pkgs/development/libraries/gobject-introspection/default.nix``
## SRI hash ``sha256-kg0aP87ercMqz/lcLiA7MZA53UtKCN0aLf0oPRnAua4=``
## (decodes to the hex value pinned below).
##
## ## Version choice — 1.86.0 (current upstream stable)
##
## gobject-introspection follows the GNOME release cadence; 1.86.0
## is the current stable in the 1.86.x line. Matches the nixpkgs pin
## as of mid-2026.
##
## sha256 = 920d1a3fcedeadc32acff95c2e203b319039dd4b4a08dd1a2dfd283d19c0b9ae
##  (cross-checked against nixpkgs's SRI hash above; same upstream
##  download.gnome.org tarball bytes.)
##
## ## Build shape
##
## Meson + ninja. Build-time tools needed: flex, bison, pkg-config,
## python3 with ``setuptools`` + ``mako`` + ``markdown`` modules
## (surfaced via the M9.R.15d.2 ``python3-with-modules`` stdlib stub
## which wraps ``nixpkgs#python3.withPackages``). v1 elides the docs
## build (``gtk_doc=false``) so the docbook-xsl-nons + docbook-xml-dtd
## dependencies are skipped.
##
## ## Library + executable artifacts
##
## gobject-introspection's meson build emits one shared library and
## several command-line tools — v1 records the load-bearing ones:
##
##   * ``libgirepository-1.0.so`` — the runtime metadata loader (every
##                                   downstream language binding links
##                                   against this).
##   * ``g-ir-scanner``           — the build-time scanner that emits
##                                   .gir XML from a C library.
##   * ``g-ir-compiler``          — the .gir -> .typelib compiler.
##
## ## Configurables
##
## v1 ships NO configurables — meson options are pinned:
##
##   * ``cairo=disabled``    — drop Cairo support (cairo lives in a
##                              separate package; introspection
##                              metadata for cairo is generated by
##                              the cairo recipe, not this one).
##   * ``gtk_doc=false``     — drop the HTML docs build.
##   * ``tests=false``       — skip the upstream test suite.
##   * ``doctool=disabled``  — drop the docbook-emit tool (depends on
##                              docbook-xsl, not in the v1 closure).

import repro_project_dsl
import repro_dsl_stdlib/constructors
import repro_dsl_stdlib/types/package_result

import ../source_recipe_paths

# ---------------------------------------------------------------------------
# Package declaration
# ---------------------------------------------------------------------------

package gobjectIntrospectionSource:
  ## From-source gobject-introspection — GNOME-stack foundation for
  ## gtk4 (build-time only in v1) and every downstream introspected
  ## library.

  versions:
    "1.86.0":
      sourceRevision = "1.86.0"
      sourceUrl = "https://download.gnome.org/sources/gobject-introspection/1.86/gobject-introspection-1.86.0.tar.xz"
      sourceRepository = "https://gitlab.gnome.org/GNOME/gobject-introspection"

  fetch:
    url: "https://download.gnome.org/sources/gobject-introspection/1.86/gobject-introspection-1.86.0.tar.xz"
    sha256: "920d1a3fcedeadc32acff95c2e203b319039dd4b4a08dd1a2dfd283d19c0b9ae"
    extractStrip: 1

  nativeBuildDeps:
    "meson >=0.62"
    "ninja >=1.10"
    "gcc >=11"
    ## Meson resolves glib2 and libffi through their generated .pc files.
    "pkg-config"
    ## flex generates the GIR lexer at build time.
    "flex"
    ## bison generates the GIR parser at build time.
    "bison"
    ## python3 + the mako/markdown packages run the scanner's
    ## template-driven code generators. M9.R.15d.2 introduced the
    ## ``python3-with-modules`` stdlib stub that wraps python3 with
    ## ``setuptools``, ``mako`` and ``markdown`` pre-loaded — bare
    ## ``python3`` is insufficient because the scanner's startup
    ## ``import mako`` short-fails on a plain interpreter.
    "python3-with-modules"

  buildDeps:
    ## glib2 is the foundation library (libgirepository links against
    ## libgobject + libglib + libgio).
    "glib2 >=2.62"
    ## libffi is required for libgirepository's runtime closure layer
    ## (every introspected callback / signal handler is dispatched
    ## through a libffi-built closure).
    "libffi"

  config:
    discard

  library libGirepository:
    ## ``libgirepository-1.0.so`` — the runtime metadata loader.
    discard

  executable gIrScanner:
    ## ``/usr/bin/g-ir-scanner`` — build-time scanner.
    discard

  executable gIrCompiler:
    ## ``/usr/bin/g-ir-compiler`` — .gir to .typelib compiler.
    discard

  executable gobjectIntrospection:
    ## M9.R.15g.1 — alias artefact so the from-source resolver matches
    ## the dep selector ``"gobject-introspection"`` to this recipe
    ## without the canonical-prefix tier needing to reason about the
    ## ``g-ir-*`` binary naming convention. The build block stages
    ## ``g-ir-scanner`` at ``.repro/output/gobject-introspection/
    ## gobject-introspection`` via ``pkg.executableAlias(...)``; the
    ## actual entry-point is still ``g-ir-scanner`` (consumers walk
    ## the install-mirror's ``usr/bin/`` directly when invoking the
    ## scanner — the alias only serves the resolver's name-match).
    name: "gobject-introspection"
    discard

  build:
    setCurrentOwningPackageOverride("gobjectIntrospectionSource")
    try:
      let opts = @[
        "cairo=disabled",
        "gtk_doc=false",
        "tests=false",
        "doctool=disabled",
        # M9.R.16.3 — pin ``libdir=lib`` (overrides meson's default of
        # ``lib64``). The upstream ``g-ir-scanner`` script (installed
        # to ``$prefix/bin``) computes its ``pylibdir`` relocatably as
        # ``$prefix/../lib/gobject-introspection``. When meson uses the
        # default ``lib64``, the ``giscanner`` Python module lands at
        # ``$prefix/lib64/gobject-introspection/giscanner/`` and the
        # scanner's relocatable probe misses it, falling through to a
        # hard-coded ``/usr/lib64/gobject-introspection`` (also missing
        # in the install-mirror), and the scanner aborts with
        # ``ModuleNotFoundError: No module named 'giscanner'`` during
        # any downstream ``g-ir-scanner`` call (e.g. gdm's
        # ``libgdm/Gdm-1.0.gir`` step). Pinning ``libdir=lib`` keeps
        # the relocatable probe happy. The install-mirror's pkg-config
        # rewrite path already handles both ``lib`` and ``lib64``
        # (``package_result.nim:1020-1021``).
        "libdir=lib",
      ]
      let pkg = meson_package(
        srcDir = "./src",
        configureOptions = opts,
        extraEnv = @[
          ("PYTHONNOUSERSITE", "1"),
          # libgirepository directly uses libm. On Nix hosts the final helper
          # links do not inherit a global FHS library search path, so let ld
          # resolve libm from the source-built glibc mirror without exposing
          # that runtime through LD_LIBRARY_PATH to build tools.
          ("LDFLAGS", "-Wl,-rpath-link," & sourcePackageInstallPath(
            "glibc", "usr", "lib64")),
        ],
        srcPatches = @[
          "sed -i '1s|.*|#!/usr/bin/env python3-with-modules|' src/tools/g-ir-tool-template.in",
          "sed -i \"s/if not os.path.isfile(os.path.join(pylibdir, 'giscanner', '_giscanner' + py_mod_suffix)):/if not os.path.isdir(os.path.join(pylibdir, 'giscanner')):/\" src/tools/g-ir-tool-template.in",
          # Nix's Meson carries support for private GIR install directories
          # through this scanner option. Keep the source-built scanner
          # compatible while preserving ordinary FHS library names by default.
          "sed -i '/parser.add_option(\"-L\", \"--library-path\",/i\\    parser.add_option(\"\", \"--fallback-library-path\", action=\"store\", dest=\"fallback_libpath\", default=\"\", help=\"Path to prepend to resolved shared libraries\")' src/giscanner/scannermain.py",
          "sed -i 's@return list(map(sanitize_shlib_path, shlibs))@fallback_libpath = options.fallback_libpath or \"\"; return list(map(lambda p: os.path.join(fallback_libpath, p), map(sanitize_shlib_path, shlibs)))@' src/giscanner/shlibs.py"
        ])
      discard pkg.library("libGirepository")
      discard pkg.executableAlias("g-ir-scanner", sourceName = "g-ir-scanner")
      discard pkg.executable("gIrCompiler")
      # M9.R.15g.1 — alias ``gobject-introspection`` to ``g-ir-scanner``
      # so consumers writing ``nativeBuildDeps: "gobject-introspection"``
      # match this recipe at the resolver's tier-0 exact-match level.
      discard pkg.executableAlias("gobject-introspection",
        sourceName = "g-ir-scanner")
    finally:
      clearCurrentOwningPackageOverride()

  runtimeDeps:
    "glib2 >=2.62"
    "libffi"
    "glibc >=2.29"
