## Source-from-tarball binutils recipe — M9.N Batch E compiler-chain
## slice.
##
## binutils is the GNU binary utilities collection: the canonical host
## linker / assembler / archiver / object-file inspector toolchain
## every from-source recipe under ``recipes/packages/source/`` that
## drives gcc transitively consumes at link + assemble + strip time.
## The Batch E (gcc + binutils + make) slice sits BELOW Batch D (cmake
## + autoconf + automake + libtool + pkgconf) in the bootstrap
## layering: every Batch D autotools recipe ultimately shells out to
## ``ld`` / ``as`` / ``ar`` from binutils. R5 musl-tcc is the long-
## term clean root for the bootstrap chain; Batch E ships the recipes
## against the existing upstream tarballs as declarative shape so the
## M9.K convention layer can lower them when the recipe graph asks for
## the host binary-utilities toolchain.
##
## ## Convention chosen — ``from-source-autotools``
##
## binutils is itself an autotools-driven project: the upstream
## release tarball ships a ``./configure`` script generated by
## autoconf + ``Makefile.in`` files generated by automake at the
## source root, so the canonical ``./configure && make && make
## install`` cycle suffices. The ``from-source-autotools`` convention
## (M9.L.2) claims the recipe via the populated ``configureFlags:``
## channel.
##
## The release archive already contains generated parsers. The recipe
## therefore omits maintainer-only parser generators and suppresses
## optional manuals and gprofng to keep the bootstrap closure minimal.
##
## ## Why binutils matters for the v1 desktop story
##
## binutils is the binary-utilities toolchain every C / C++ recipe in
## ``recipes/packages/source/`` that produces a linkable artifact
## (executables / shared libraries / static archives) depends on:
## every gcc invocation shells out to ``ld`` at link time, every
## archive build invokes ``ar`` + ``ranlib``, every strip pass runs
## ``strip``, every readelf-based probe shells through ``readelf``.
## Bootstrapping binutils from source closes the host binary-
## utilities floor the entire C / C++ ecosystem pins.
##
## ## sha256 strategy
##
## The fetch URL points at the upstream ftp.gnu.org release tarball
## ``binutils-2.43.tar.xz``. The sha256 was computed locally by
## downloading the tarball and running ``sha256sum`` over the bytes.
## nixpkgs's ``pkgs/development/tools/misc/binutils/default.nix``
## consumes the same ftp.gnu.org tarball via fetchurl so the cross-
## check holds when both pin the same version.
##
## ## Version choice — 2.43 (per task brief)
##
## binutils releases are cut on ftp.gnu.org under tags of the form
## ``binutils-<X>.<Y>``. 2.43 is the latest stable in the 2.43.x line
## as of the task brief. The 2.43 cut introduced the
## ``--enable-default-execstack=no`` defence-in-depth default + the
## RISC-V ZBA / ZBB / ZBC extension support; anything ``>=2.39``
## covers the kernel-recipe pinning and every consumer's binutils
## floor.
##
## ## Why binutils is NOT vendored
##
## The ``binutils-2.43.tar.xz`` tarball weighs ~27 MB which is well
## below GitHub's 100-MB single-file ceiling, but the Batch D + E
## precedents (cmake / autoconf / automake / libtool / pkgconf / gcc)
## all use live upstream URLs directly — no vendor/ copy. binutils
## follows the same precedent. A future R5 musl-tcc vendoring pass
## will host the bootstrap-critical archives on a reprobuild-managed
## mirror.
##
## ## Artifacts
##
## binutils exposes ELEVEN load-bearing CLI binaries on disk:
##
##   * ``ld``        — ``$PREFIX/bin/ld``, the canonical linker every
##                      gcc / g++ invocation shells out to at link
##                      time. The ``--enable-ld=default`` configure
##                      flag pins the ``ld`` binary to be the
##                      classical BFD linker (vs gold / lld).
##   * ``as``        — ``$PREFIX/bin/as``, the GNU assembler every
##                      gcc invocation shells out to for the
##                      ``.s`` -> ``.o`` pass.
##   * ``ar``        — ``$PREFIX/bin/ar``, the archive builder every
##                      static-library build invokes to bundle
##                      ``.o`` files into a ``.a`` archive.
##   * ``nm``        — ``$PREFIX/bin/nm``, the symbol-table dumper
##                      every linker-debug session reaches for.
##   * ``objcopy``   — ``$PREFIX/bin/objcopy``, the object-file
##                      surgeon (rename / strip / extract sections /
##                      convert formats) the kernel build invokes
##                      during the ``arch/x86/boot/`` pass.
##   * ``objdump``   — ``$PREFIX/bin/objdump``, the disassembler +
##                      object-file inspector every reverse-
##                      engineering / debugging workflow consumes.
##   * ``ranlib``    — ``$PREFIX/bin/ranlib``, the archive-index
##                      generator paired with ``ar`` for legacy
##                      archives that need an explicit symbol table.
##   * ``strip``     — ``$PREFIX/bin/strip``, the symbol-stripper
##                      every release-build pass invokes to remove
##                      debug + symbol-table sections from shipped
##                      binaries.
##   * ``readelf``   — ``$PREFIX/bin/readelf``, the ELF-format
##                      inspector every loader-debug session +
##                      every autotools ``./configure`` probe for
##                      DT_NEEDED / RPATH / SONAME shells through.
##   * ``size``      — ``$PREFIX/bin/size``, the section-size
##                      reporter that summarises text / data / bss
##                      footprint for a binary.
##   * ``strings``   — ``$PREFIX/bin/strings``, the printable-ASCII-
##                      extractor that surfaces string literals from
##                      a binary (forensics / reverse-engineering
##                      staple).
##
## ## Configurables
##
## The configure invocation selects the linker features needed by the
## desktop package set while omitting optional tools and documentation:
##
##   * ``--enable-gold``      — enable the gold linker as a sidecar
##                               binary. gold is a faster, more-
##                               parallel linker for ELF targets;
##                               retaining it gives consumer
##                               recipes a choice between BFD ld and
##                               gold.
##   * ``--enable-ld=default`` — pin the ``$PREFIX/bin/ld`` binary
##                                to be the classical BFD linker (vs
##                                making gold the default). The
##                                classical BFD ld is the more
##                                conservative default that every
##                                consumer recipe expects to find.
##   * ``--enable-plugins``    — build with linker-plugin support so
##                                gcc's LTO pass can hand object
##                                files to a plugin-loaded helper
##                                at link time.
##   * ``--enable-shared``     — emit the binutils libraries as
##                                shared objects (libbfd.so /
##                                libopcodes.so / libctf.so) in
##                                addition to the static archives.
##                                The desktop-baseline recipes that
##                                link against libbfd at runtime
##                                (the ``binutils-devel`` consumer
##                                family) need the .so variants.
##   * ``--disable-werror``    — treat compiler warnings as warnings,
##                                not errors. The upstream binutils
##                                tree occasionally trips ``-Werror``
##                                on newer gcc / clang versions; the
##                                task brief specifies this defence-
##                                in-depth flag to keep the build
##                                resilient to host-compiler version
##                                drift.
##   * ``--disable-gprofng``   — omit the optional profiler, whose
##                                generated sources add bison and flex
##                                to the build-time closure.
##   * ``MAKEINFO=true``       — suppress Info manual generation so
##                                the boot image does not require
##                                texinfo to build binutils.

import repro_project_dsl
import repro_dsl_stdlib/constructors
import repro_dsl_stdlib/types/package_result

# ---------------------------------------------------------------------------
# Package declaration
# ---------------------------------------------------------------------------

package binutilsSource:
  ## From-source binutils — M9.N Batch E compiler-chain slice.
  ##
  ## Tier-2b from-source-autotools convention consumer: the
  ## convention layer reads the ``fetch:`` block (registered via
  ## ``registeredFetchSpec``) and the ``configureFlags:`` block
  ## (registered via ``registeredBuildFlags`` on the ``"configure"``
  ## channel) and lowers them into fetch + configure + build + install
  ## BuildActions. Eleven executable artifact recipe.

  versions:
    ## Pinned upstream tag. ``sourceUrl`` records the canonical
    ## ftp.gnu.org release tarball URL; ``sourceRepository`` points
    ## at the canonical sourceware.org git tree.
    "2.43":
      sourceRevision = "binutils-2_43"
      sourceUrl = "https://ftp.gnu.org/gnu/binutils/binutils-2.43.tar.xz"
      sourceRepository = "https://sourceware.org/git/binutils-gdb.git"

  fetch:
    ## Live upstream URL — NOT vendored, per the Batch D + E
    ## precedent. A future R5 musl-tcc vendoring pass will host the
    ## bootstrap-critical archives on a reprobuild-managed mirror.
    ##
    ## sha256 computed locally over the upstream ftp.gnu.org
    ## tarball; nixpkgs consumes the same tarball via fetchurl so
    ## the cross-check holds when both pin the same version.
    url: "https://ftp.gnu.org/gnu/binutils/binutils-2.43.tar.xz"
    sha256: "b53606f443ac8f01d1d5fc9c39497f2af322d99e14cea5c0b4b124d630379365"
    extractStrip: 1

  nativeBuildDeps:
    ## gcc is the host C toolchain — binutils is C99 with a handful
    ## of C++ helpers in gold + libctf. The version pin matches the
    ## gccSource recipe in this batch.
    "gcc >=11"
    ## make is the build-system driver — the from-source-autotools
    ## convention's compile action invokes ``make`` after
    ## ``./configure``.
    "make >=4.3"
    ## perl is invoked by binutils's ``configure`` script for a
    ## handful of code-generation passes under ``binutils/`` and
    ## ``ld/``.
    "perl >=5.32"
    ## Release tarballs carry generated parsers, so bison and flex are
    ## maintainer-only dependencies. Info manuals are intentionally omitted
    ## below and do not add texinfo to the boot-image source closure.

  buildDeps:
    discard

  config:
    ## No prefix lifted from `configureFlags:`; flags inlined in the `build:` block.
    discard
  executable ld:
    ## ``$PREFIX/bin/ld`` — the classical BFD linker, pinned as the
    ## default by the ``--enable-ld=default`` configure flag. Every
    ## gcc / g++ invocation shells out to ``ld`` at link time. v1
    ## records the artifact only.
    discard

  executable "as":
    ## ``$PREFIX/bin/as`` — the GNU assembler. String-form artifact
    ## declaration because ``as`` is a reserved Nim keyword for type
    ## conversions; the M3 artifact registry stores the literal
    ## ``"as"`` string. v1 records the artifact only.
    discard

  executable ar:
    ## ``$PREFIX/bin/ar`` — the archive builder every static-
    ## library build invokes. v1 records the artifact only.
    discard

  executable nm:
    ## ``$PREFIX/bin/nm`` — the symbol-table dumper. v1 records the
    ## artifact only.
    discard

  executable objcopy:
    ## ``$PREFIX/bin/objcopy`` — the object-file surgeon (rename /
    ## strip / extract sections / convert formats). v1 records the
    ## artifact only.
    discard

  executable objdump:
    ## ``$PREFIX/bin/objdump`` — the disassembler + object-file
    ## inspector. v1 records the artifact only.
    discard

  executable ranlib:
    ## ``$PREFIX/bin/ranlib`` — the archive-index generator. v1
    ## records the artifact only.
    discard

  executable strip:
    ## ``$PREFIX/bin/strip`` — the symbol-stripper. v1 records the
    ## artifact only.
    discard

  executable readelf:
    ## ``$PREFIX/bin/readelf`` — the ELF-format inspector. v1
    ## records the artifact only.
    discard

  executable size:
    ## ``$PREFIX/bin/size`` — the section-size reporter. v1 records
    ## the artifact only.
    discard

  executable strings:
    ## ``$PREFIX/bin/strings`` — the printable-ASCII-extractor. v1
    ## records the artifact only.
    discard

  build:
    ## M9.R.5b — explicit `build:` block constructed from the lifted `config:` values + the inlined verbatim flags. Calls the M9.R.2b high-level `autotools_package(...)` constructor.
    setCurrentOwningPackageOverride("binutilsSource")
    try:
      let opts = @[
        "--enable-gold",
        "--enable-ld=default",
        "--enable-plugins",
        "--enable-shared",
        "--disable-werror",
        "--disable-gprofng",
        "MAKEINFO=true",
      ]
      let pkg = autotools_package(srcDir = "./src", configureOptions = opts)
      discard pkg.executable("ld")
      discard pkg.executable("as")
      discard pkg.executable("ar")
      discard pkg.executable("nm")
      discard pkg.executable("objcopy")
      discard pkg.executable("objdump")
      discard pkg.executable("ranlib")
      discard pkg.executable("strip")
      discard pkg.executable("readelf")
      discard pkg.executable("size")
      discard pkg.executable("strings")
    finally:
      clearCurrentOwningPackageOverride()

  runtimeDeps:
    ## TODO(M9.R.5b): derive runtime closure from pkg-config /
    ## DT_NEEDED inspection of the linked artifacts. Empty until
    ## the M9.R.5b per-recipe pass populates per-output ELF
    ## interrogation.
    discard
