## Source-from-tarball automake recipe — M9.N Batch D build-tool slice.
##
## automake is the GNU build system's ``Makefile.in`` generator: it
## processes ``Makefile.am`` templates into portable ``Makefile.in``
## files the autoconf-generated ``./configure`` script consumes. The
## upstream tarball ships a pre-generated ``./configure`` so the
## standard ``./configure && make && make install`` cycle suffices.
##
## ## Convention chosen — ``from-source-autotools``
##
## automake is itself an autotools-driven project: the upstream
## release tarball ships a ``./configure`` script generated by
## autoconf. The ``from-source-autotools`` convention (M9.L.2) claims
## the recipe via the populated ``configureFlags:`` channel.
##
## ## Why automake matters for the v1 desktop story
##
## automake is the ``Makefile.am`` → ``Makefile.in`` generator the
## entire autotools-driven C / C++ ecosystem relies on: every
## autotools-driven recipe in ``recipes/packages/source/`` re-runs
## ``automake`` when the shipped ``Makefile.in``s are missing or
## stale. Bootstrapping automake from source closes the
## ``uses: "automake"`` toolchain floor.
##
## ## sha256 strategy
##
## The fetch URL points at the upstream ftp.gnu.org release tarball
## ``automake-1.17.tar.xz``. The sha256 was computed locally by
## downloading the tarball and running ``sha256sum`` over the bytes.
## nixpkgs's ``pkgs/development/tools/misc/automake/automake-1.18.x.nix``
## pins automake 1.18.1 with SRI
## ``sha256-FoqjYyeDUbia9WaERI9SWlvOUHnQtoQr2RD90/FkaIc=``, NOT the
## 1.17 release the task brief requests, so the nixpkgs cross-check
## is deferred to the follow-up pass that lifts automake to nixpkgs's
## 1.18 line.
##
## ## Version choice — 1.17 (per task brief)
##
## automake releases are cut on ftp.gnu.org under tags of the form
## ``automake-<X>.<Y>``. 1.17 is the last stable in the 1.17 line
## before 1.18 nixpkgs pinned; anything ``>=1.16`` covers every
## consumer's automake pinning.
##
## ## Artifacts
##
## automake exposes two load-bearing CLI binaries on disk:
##
##   * ``automake`` — ``$PREFIX/bin/automake``, the canonical
##                     ``Makefile.am`` → ``Makefile.in`` generator.
##   * ``aclocal``  — ``$PREFIX/bin/aclocal``, generates ``aclocal.m4``
##                     from the system + project M4 macro tree
##                     (``/usr/share/aclocal/`` + ``m4/`` in the
##                     project) so autoconf can find third-party
##                     macros.
##
## ## Configurables
##
## v1 ships ONE configure flag — ``--disable-static`` — mirroring the
## modern-desktop baseline. automake itself is Perl-implemented so
## the static/shared distinction barely applies, but the flag is
## preserved for consistency with the other autotools recipes.

import repro_project_dsl
import repro_dsl_stdlib/constructors
import repro_dsl_stdlib/types/package_result

# ---------------------------------------------------------------------------
# Package declaration
# ---------------------------------------------------------------------------

package automakeSource:
  ## From-source automake — M9.N Batch D build-tool slice.
  ##
  ## Tier-2b from-source-autotools convention consumer: the
  ## convention layer reads the ``fetch:`` block (registered via
  ## ``registeredFetchSpec``) and the ``configureFlags:`` block
  ## (registered via ``registeredBuildFlags`` on the ``"configure"``
  ## channel) and lowers them into fetch + configure + build + install
  ## BuildActions. Two executable artifact recipe.

  versions:
    ## Pinned upstream tag. ``sourceUrl`` records the canonical
    ## ftp.gnu.org release tarball URL; ``sourceRepository`` points
    ## at the canonical savannah.gnu.org mirror.
    "1.17":
      sourceRevision = "v1.17"
      sourceUrl = "https://ftp.gnu.org/gnu/automake/automake-1.17.tar.xz"
      sourceRepository = "https://git.savannah.gnu.org/git/automake.git"

  fetch:
    ## Live upstream URL. The vendor/ directory is reserved for a
    ## follow-up vendoring pass.
    ##
    ## sha256 computed locally over the upstream ftp.gnu.org tarball;
    ## nixpkgs cross-check deferred because nixpkgs pins automake
    ## 1.18.1 (not the 1.17 the task brief requests).
    url: "https://ftp.gnu.org/gnu/automake/automake-1.17.tar.xz"
    sha256: "8920c1fc411e13b90bf704ef9db6f29d540e76d232cb3b2c9f4dc4cc599bd990"
    extractStrip: 1

  nativeBuildDeps:
    ## autoconf is automake's primary peer in the autotools chain;
    ## the ``automake`` driver consumes ``configure.ac`` to know
    ## which ``Makefile.am`` templates to process.
    "autoconf"
    ## perl is the implementation language for automake's CLI driver.
    "perl >=5.32"
    ## make is the build-system driver — the from-source-autotools
    ## convention's compile action invokes ``make`` after
    ## ``./configure``.
    "make"

  config:
    ## No prefix lifted from `configureFlags:`; flags inlined in the `build:` block.
    discard
  executable automake:
    ## ``$PREFIX/bin/automake`` — the canonical ``Makefile.am`` →
    ## ``Makefile.in`` generator. v1 records the artifact only.
    discard

  executable aclocal:
    ## ``$PREFIX/bin/aclocal`` — generates ``aclocal.m4`` from the
    ## system + project M4 macro tree so autoconf can find third-
    ## party macros. v1 records the artifact only.
    discard

  build:
    ## M9.R.5b — explicit `build:` block constructed from the lifted `config:` values + the inlined verbatim flags. Calls the M9.R.2b high-level `autotools_package(...)` constructor.
    setCurrentOwningPackageOverride("automakeSource")
    try:
      let opts = @[
        "--disable-static",
      ]
      let pkg = autotools_package(srcDir = "./src", configureOptions = opts)
      discard pkg.executable("automake")
      discard pkg.executable("aclocal")
    finally:
      clearCurrentOwningPackageOverride()

  runtimeDeps:
    ## TODO(M9.R.5b): derive runtime closure from pkg-config /
    ## DT_NEEDED inspection of the linked artifacts. Empty until
    ## the M9.R.5b per-recipe pass populates per-output ELF
    ## interrogation.
    discard
