"""Maintain the source-test inventory without importing package recipes."""

import argparse
import json
from pathlib import Path
import sys


def discover(root: Path) -> list[str]:
    source = root / "packages" / "source"
    paths = sorted(
        path.relative_to(root).as_posix()
        for pattern in ("test_*.nim", "*/test_*.nim")
        for path in source.glob(pattern)
        if path.is_file()
    )
    if not paths:
        raise ValueError("no source recipe tests found")
    names: set[str] = set()
    for path in paths:
        name = Path(path).stem.replace("_", "-")
        if name in names:
            raise ValueError(f"duplicate source-test target: {name}")
        names.add(name)
    return paths


def render(paths: list[str]) -> str:
    lines = [
        "# Generated by scripts/source_test_catalog.py; do not edit.",
        "const sourceTestFiles* = [",
        *(f"  {json.dumps(path)}," for path in paths),
        "]",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    try:
        paths = discover(args.root)
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1
    expected = render(paths)
    target = args.root / "source_tests.nim"
    if args.write:
        target.write_text(expected, encoding="utf-8", newline="\n")
    elif not target.is_file() or target.read_text(encoding="utf-8") != expected:
        print("Source-test inventory is stale; run repro run refresh-source-tests.",
              file=sys.stderr)
        return 1
    print(f"Validated {len(paths)} source-test graph entries.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
