## Source-from-tarball btrfs-progs recipe — closes M9.R.27 Gap 4 (G4).
##
## btrfs-progs ships the canonical Btrfs userspace utilities
## (``mkfs.btrfs``, ``btrfs``, ``btrfsck``, ``btrfs-image``,
## ``btrfs-tune``). autotools convention.
##
## Vendored at ``recipes/packages/source/btrfs-progs/vendor/btrfs-progs-v7.0.tar.xz``.
## sha256 = c286d6876cbcd72327a0b417e4cfd280353ec23e37b549fdbcd7800a832d9a99
## (4,989,268 bytes).

import repro_project_dsl
import repro_dsl_stdlib/constructors
import repro_dsl_stdlib/types/package_result

package btrfsProgsSource:
  versions:
    "7.0":
      sourceRevision = "v7.0"
      sourceUrl = "https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v7.0.tar.xz"
      sourceRepository = "https://github.com/kdave/btrfs-progs"

  fetch:
    url: "https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v7.0.tar.xz"
    sha256: "c286d6876cbcd72327a0b417e4cfd280353ec23e37b549fdbcd7800a832d9a99"
    extractStrip: 1

  nativeBuildDeps:
    "autoconf"
    "automake"
    "libtool"
    "make"
    "gcc >=11"
    "pkg-config"

  buildDeps:
    "util-linux"   # libblkid + libuuid
    "lzo"          # transparent compression dep
    "zstd"         # transparent compression dep
    "libgcrypt"    # checksumming (sha256, blake2)
    "zlib"         # zlib compression dep
    # M9.R.29.12 — libext2fs (mkfs.btrfs --rootdir support) deferred;
    # the sibling-recipe resolver doesn't currently bridge to the
    # 'e2fsprogs' from-source recipe (different selector naming
    # vs the project_dsl 'e2fsprogsSource' identifier), and we
    # don't ship a nix-fallback stub either. The installer doesn't
    # need --rootdir; configure with --disable-ext2 instead.

  config:
    discard
  executable btrfs:
    discard
  executable btrfsck:
    discard
  library libBtrfs:
    discard

  build:
    setCurrentOwningPackageOverride("btrfsProgsSource")
    try:
      let opts = @[
        "--disable-static",
        "--enable-shared",
        "--disable-documentation",
        "--disable-python",
        "--disable-zoned",
        "--disable-libudev",
        "--disable-convert",
      ]
      ## M9.R.29.12c — btrfs-progs uses an in-tree Makefile (the
      ## upstream Makefile lives in src/Makefile, generated by
      ## configure from src/Makefile.in). The standard
      ## ``autotools_package`` out-of-tree pattern leaves ``build/``
      ## without a Makefile; pin ``buildDir = "src"`` so configure
      ## emits the Makefile next to the sources and make finds it.
      let pkg = autotools_package(srcDir = "./src", buildDir = "src",
                                  configureOptions = opts)
      discard pkg.executable("btrfs")
      discard pkg.executableAlias("mkfsBtrfs", "mkfs.btrfs")
      discard pkg.executable("btrfsck")
      discard pkg.executableAlias("btrfsImage", "btrfs-image")
      discard pkg.executableAlias("btrfsTune", "btrfstune")
      discard pkg.library("libBtrfs")
    finally:
      clearCurrentOwningPackageOverride()

  runtimeDeps:
    discard
